version: '3.9'

services:
  app:
    #build: .
    image: sergivnik/pet-proect-app:latest
    ports:
      - '80:80'
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SESSION_SECRET=${SESSION_SECRET}
      - NODE_ENV=${NODE_ENV}
    restart: always
    volumes:
      - ./API/Bills:/app/API/Bills
      - ./API/contracts:/app/API/contracts
      - ./API/DriverBills:/app/API/DriverBills

  db:
    image: mysql:8
    env_file:
      - .env
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  mysql_data:
