export const initialStore = {
  dateList: [],
  filteredDateList: [],
  driverlist: [],
  filteredDrivers: [],
  clientList: [],
  filteredClients: [],
  citieslist: [],
  filteredLoading: [],
  filteredUnloading: [],
  odersList: [],
  originOdersList: [],
  driverOrderList: [],
  filteredCustomerPrice: [],
  filteredDriverPrice: [],
  statusCustomerPay: [
    { _id: 1, value: 'Ок' },
    { _id: 2, value: 'Нет' },
    { _id: 3, value: 'Мыло' },
    { _id: 4, value: 'Печать' },
    { _id: 5, value: 'Почта' },
    { _id: 6, value: 'Обещал оплату' },
    { _id: 7, value: 'Отдал клиенту' },
    { _id: 8, value: 'Частично оплачен' },
  ],
  filteredStatusCustomerPayment: [],
  accountList: [],
  filteredAccountList: [],
  customerWithoutPayment: [],
  customerPaymentsList: [],
  income: 0,
  expenses: 0,
  request: {},
  driverDebtList: [],
  contractorsList: [],
  contractorsPayments: [],
  driverpayments: [],
  trackdrivers: [],
  tracklist: [],
  clientmanager: [],
  message: null,
  addtable: [],
  storelist: [],
  incomereport: [],
  yearconst: {},
  currentUser: { name: null, role: null },
  currentOwner: {},
};
