export const initialStore = {
  dateList: [],
  filteredDateList: [],
  driverlist: [],
  filteredDrivers: [],
  clientList: [],
  filteredClients: [],
  citieslist: [],
  filteredLoading: [],
  filteredUnloading: [],
  odersList: [],
  maxCustomerPrice: 0,
  minCustomerPrice: 0,
  maxDriverPrice: 0,
  minDriverPrice: 0,
  request: {
    status: "IDLE",
    error: null,
  },
};
